### ISSUE TITLE
Question consultation

### ISSUE THREAD

**Issue by yaolp123** [ZhihuaLiuEd/canetbrats#6]
Dear authors: 
    Recently I  have looking your this project and feel interested in it !could have a dataset of this project?  On this web: https://www.med.upenn.edu/cbica/brats2020/  I could not find the dataset. Thanks a lot! I am looking forward to your reply Sincerely!

Best regards.

**Comment by ZhihuaLiuEd** [comment]
Hi there:
For BraTS2020, you can refer: https://www.med.upenn.edu/cbica/brats2020/data.html 
The webpage contains everything regards on data application.
I believe you also have to register an account at https://ipp.cbica.upenn.edu/ by agree various terms and conditions in order to download the data.
